fix runtime crash in macos26 with objc2 because of sign encoding
> thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-foundation-0.2.2/src/generated/NSEnumerator.rs:7:1:
> invalid message send to -[_TtGCs23_ContiguousArrayStorageCSo8NSScreen_$ countByEnumeratingWithState:objects:count:]: expected return to have type code 'q', but found 'Q'

See: https://github.com/madsmtm/objc2/issues/765 for more details